use hqt;
insert into ma_lop (ma_lop, ten_nganh_fk) values ("A-E", "Công nghệ hàng không vũ trụ");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("C-A-CLC1", "Khoa học máy tính");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("C-A-CLC2", "Khoa học máy tính");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("C-A-CLC3", "Khoa học máy tính");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("C-B", "Công nghệ thông tin");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("C-C", "Công nghệ thông tin");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("C-CLC", "Công nghệ thông tin");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("C-D", "Công nghệ thông tin");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("C-E", "Công nghệ thông tin");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("J", "Công nghệ thông tin định hướng thị trường Nhật Bản");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("T-CLC", "Hệ thống thông tin");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("N-CLC", "Mạng máy tính và truyền thông dữ liệu");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("ĐA-CLC", "Công nghệ kỹ thuật điện tử - viễn thông");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("K", "Kỹ thuật máy tính");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("R", "Kỹ thuật Robot");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("E", "Kỹ thuật năng lượng");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("V", "Vật lý kỹ thuật");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("H", "Cơ kỹ thuật");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("M", "Công nghệ kỹ thuật cơ điện tử");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("AT", "Kỹ thuật điều khiển và tự động hóa");
insert into ma_lop (ma_lop, ten_nganh_fk) values ("XD", "Công nghệ kỹ thuật xây dựng");
insert into ma_lop (ma_lop, ten_nganh_fk)values ("AI", "Trí tuệ nhân tạo");